#!/usr/bin/env python3
"""Generate synthesizable Verilog for a DWN inference core from an exported model.

Reads a dwn_*.json export (see verification/export_model.py) and emits, into an
output directory (default rtl/generated/):

  dwn_layer<i>.v  one module per LUT layer: lut_node instances with their truth
                  tables baked in as INIT parameters and their input pins wired
                  per the resolved mapping
  dwn_core.v      chains those layers into one in -> out module, registering
                  each layer's output
  dwn_params.vh   model-shape `defines shared with the hand-written wrapper

Any number of LUT layers is supported. Depth is a property of the model JSON,
not of the RTL: the layer count only ever appears here and in dwn_core, so a
deeper model needs no hand edits. dwn_core exists precisely because Verilog
cannot instantiate a run of differently-named modules from a generate loop --
the chain has to be unrolled by whoever knows the depth, which is this script.
It also owns the pipeline registers, so the hand-written wrapper sees one
fixed-shape module regardless of depth.

dwn_core is wired into groupsum -> argmax by rtl/dwn_uart_top.v (the only
top-level module -- there is no separate combinational top; a 2352-bit parallel
input bus isn't representative of the real hardware, which only ever sees the
vector one UART byte at a time), so simulate/synthesize with both directories on
the source list.

Conventions match verification/hw_model.py exactly: little-endian LUT
addressing (pin k -> weight 2**k, so address bit k is driven by input
mapping[k]), contiguous GroupSum groups, argmax ties to the lowest class.
Thermometer encoding stays host-side; the core input is the already-binarized
vector. Everything emitted is plain Verilog-2001 with no vendor primitives --
iCE40 mapping happens later via yosys synth_ice40, and the same files run under
Icarus/Verilator/cocotb.

Usage:
  python rtl/generate_rtl.py verification/exported/dwn_400_200_tau1.3.json
  python rtl/generate_rtl.py model.json -o some/other/dir
"""

import argparse
import json
from pathlib import Path


def clog2(x):
    return max(1, (x - 1).bit_length())


def lut_init(table):
    """Truth table (list indexed by address) -> Verilog INIT literal."""
    width = len(table)
    value = 0
    for addr, bit in enumerate(table):
        value |= (bit & 1) << addr
    hex_digits = (width + 3) // 4
    return f"{width}'h{value:0{hex_digits}X}"


def header(model_name):
    return (f"// Auto-generated by rtl/generate_rtl.py from {model_name}.\n"
            f"// Do not edit by hand -- regenerate instead.\n")


def emit_layer(index, layer, in_bits, model_name):
    mapping = layer["mapping"]
    luts = layer["luts"]
    num_luts = len(mapping)
    n = len(mapping[0])

    lines = [header(model_name)]
    lines.append(f"module dwn_layer{index} (")
    lines.append(f"    input  wire [{in_bits - 1}:0] in,")
    lines.append(f"    output wire [{num_luts - 1}:0] out")
    lines.append(");")
    for i in range(num_luts):
        # Address bit k is driven by in[mapping[k]]; Verilog concatenation
        # lists MSB first, so pins go in reverse order.
        pins = ", ".join(f"in[{mapping[i][k]}]" for k in reversed(range(n)))
        lines.append(
            f"    lut_node #(.N({n}), .INIT({lut_init(luts[i])})) "
            f"lut{i} (.addr({{{pins}}}), .out(out[{i}]));"
        )
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def emit_core(layer_sizes, in_bits, model_name):
    """Chain the generated layers into one registered in -> out module.

    Each layer's output is registered (layer<i>_bits), making the core an
    N-stage pipeline whose deepest combinational path is a single layer rather
    than input -> scores. Those registers are also hard synthesis boundaries:
    without them the whole stack collapses into one combinational cone that
    yosys flattens, and the layers stop existing as distinct blocks in the
    netlist. The names matter -- iCE40 cells inherit the prefix of the register
    they drive, so `layer<i>_bits` is what keeps each layer greppable in the
    netlist and selectable in the nextpnr floorplan.
    """
    out_bits = layer_sizes[-1]

    lines = [header(model_name)]
    lines.append("module dwn_core (")
    lines.append("    input  wire clk,")
    lines.append(f"    input  wire [{in_bits - 1}:0] in,")
    lines.append(f"    output wire [{out_bits - 1}:0] out")
    lines.append(");")

    for i, size in enumerate(layer_sizes, start=1):
        src = "in" if i == 1 else f"layer{i - 1}_bits"
        lines.append(f"    wire [{size - 1}:0] layer{i}_comb;")
        lines.append(f"    reg  [{size - 1}:0] layer{i}_bits = {size}'b0;")
        lines.append(f"    dwn_layer{i} u_layer{i} (.in({src}), .out(layer{i}_comb));")
        lines.append("")

    lines.append("    always @(posedge clk) begin")
    for i in range(1, len(layer_sizes) + 1):
        lines.append(f"        layer{i}_bits <= layer{i}_comb;")
    lines.append("    end")
    lines.append("")
    lines.append(f"    assign out = layer{len(layer_sizes)}_bits;")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def emit_params(meta, layer_sizes, model_name):
    """Model-shape macros shared with the hand-written UART wrapper.

    dwn_uart_top.v references these so its port widths and its settle delay
    track the generated core instead of being hand-typed. Per-layer widths are
    deliberately absent: only dwn_core needs them, and dwn_core is generated, so
    it hardcodes them. The wrapper sees just the core's outer shape plus the
    depth it has to wait for. Read this file first on the yosys/iverilog source
    list -- `define macros persist across the following files, and it is a .vh
    so the rtl/generated/*.v glob does not pick it up a second time.
    """
    in_bits = meta["input_size"]
    k = meta["k"]
    group_size = meta["group_size"]
    score_w = clog2(group_size + 1)

    lines = [header(model_name)]
    lines.append("`ifndef DWN_PARAMS_VH")
    lines.append("`define DWN_PARAMS_VH")
    lines.append(f"`define DWN_IN_BITS     {in_bits}")
    lines.append(f"`define DWN_NUM_CLASSES {k}")
    lines.append(f"`define DWN_SCORE_W     {score_w}")
    lines.append(f"`define DWN_NUM_LAYERS  {len(layer_sizes)}")
    lines.append(f"`define DWN_OUT_BITS    {layer_sizes[-1]}")
    lines.append("`endif")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate DWN inference-core Verilog from an exported model JSON.")
    parser.add_argument("model_json", type=Path, help="exported dwn_*.json model")
    parser.add_argument("-o", "--out-dir", type=Path,
                        default=Path(__file__).parent / "generated",
                        help="output directory (default: rtl/generated)")
    args = parser.parse_args()

    with open(args.model_json) as f:
        model = json.load(f)
    meta = model["meta"]
    layers = model["layers"]
    model_name = args.model_json.name

    layer_sizes = [len(l["mapping"]) for l in layers]
    assert layer_sizes == meta["layer_sizes"], "JSON layer sizes disagree with meta"

    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    in_bits = meta["input_size"]
    for i, layer in enumerate(layers, start=1):
        path = args.out_dir / f"dwn_layer{i}.v"
        path.write_text(emit_layer(i, layer, in_bits, model_name))
        written.append(path)
        in_bits = len(layer["mapping"])

    path = args.out_dir / "dwn_core.v"
    path.write_text(emit_core(layer_sizes, meta["input_size"], model_name))
    written.append(path)

    path = args.out_dir / "dwn_params.vh"
    path.write_text(emit_params(meta, layer_sizes, model_name))
    written.append(path)

    # Drop layer files left over from a deeper model. The source lists glob
    # rtl/generated/*.v, so a stale dwn_layer5.v from a previous run would be
    # compiled into a shallower design -- as dead logic under iverilog, but
    # yosys would carry the orphan module and the netlist would stop matching
    # the JSON. Silent, so remove them rather than warn.
    stale = [p for p in args.out_dir.glob("dwn_layer*.v") if p not in written]
    for p in sorted(stale):
        p.unlink()

    total_luts = sum(layer_sizes)
    print(f"model: {model_name}  (n={meta['n']}, layers={layer_sizes}, "
          f"{total_luts} LUT nodes, {meta['k']} classes x group {meta['group_size']})")
    for p in written:
        print(f"wrote {p}")
    for p in sorted(stale):
        print(f"removed stale {p}")


if __name__ == "__main__":
    main()
