// Auto-generated by rtl/generate_rtl.py from dwn_wesad_hw115_100_51_tau3.5.json.
// Do not edit by hand -- regenerate instead.

module dwn_layer2 (
    input  wire [99:0] in,
    output wire [50:0] out
);
    lut_node #(.N(4), .INIT(16'hF2FF)) lut0 (.addr({in[45], in[20], in[7], in[34]}), .out(out[0]));
    lut_node #(.N(4), .INIT(16'h0393)) lut1 (.addr({in[11], in[8], in[52], in[57]}), .out(out[1]));
    lut_node #(.N(4), .INIT(16'h1F00)) lut2 (.addr({in[47], in[38], in[53], in[79]}), .out(out[2]));
    lut_node #(.N(4), .INIT(16'h0673)) lut3 (.addr({in[85], in[89], in[44], in[92]}), .out(out[3]));
    lut_node #(.N(4), .INIT(16'hA8E8)) lut4 (.addr({in[30], in[5], in[29], in[71]}), .out(out[4]));
    lut_node #(.N(4), .INIT(16'hC8B0)) lut5 (.addr({in[36], in[3], in[42], in[28]}), .out(out[5]));
    lut_node #(.N(4), .INIT(16'hE0BA)) lut6 (.addr({in[25], in[14], in[31], in[62]}), .out(out[6]));
    lut_node #(.N(4), .INIT(16'h0457)) lut7 (.addr({in[84], in[65], in[70], in[37]}), .out(out[7]));
    lut_node #(.N(4), .INIT(16'hECFE)) lut8 (.addr({in[54], in[96], in[1], in[55]}), .out(out[8]));
    lut_node #(.N(4), .INIT(16'h0F53)) lut9 (.addr({in[16], in[4], in[76], in[0]}), .out(out[9]));
    lut_node #(.N(4), .INIT(16'hDAF8)) lut10 (.addr({in[21], in[33], in[50], in[56]}), .out(out[10]));
    lut_node #(.N(4), .INIT(16'hC54F)) lut11 (.addr({in[77], in[74], in[48], in[86]}), .out(out[11]));
    lut_node #(.N(4), .INIT(16'hD454)) lut12 (.addr({in[13], in[72], in[87], in[60]}), .out(out[12]));
    lut_node #(.N(4), .INIT(16'hAB62)) lut13 (.addr({in[80], in[41], in[64], in[23]}), .out(out[13]));
    lut_node #(.N(4), .INIT(16'hFF36)) lut14 (.addr({in[69], in[40], in[49], in[67]}), .out(out[14]));
    lut_node #(.N(4), .INIT(16'h1302)) lut15 (.addr({in[10], in[68], in[63], in[26]}), .out(out[15]));
    lut_node #(.N(4), .INIT(16'hC4D4)) lut16 (.addr({in[98], in[24], in[75], in[83]}), .out(out[16]));
    lut_node #(.N(4), .INIT(16'hCCE8)) lut17 (.addr({in[32], in[58], in[95], in[9]}), .out(out[17]));
    lut_node #(.N(4), .INIT(16'h5313)) lut18 (.addr({in[93], in[46], in[43], in[39]}), .out(out[18]));
    lut_node #(.N(4), .INIT(16'h282B)) lut19 (.addr({in[88], in[66], in[2], in[27]}), .out(out[19]));
    lut_node #(.N(4), .INIT(16'hFCC0)) lut20 (.addr({in[59], in[81], in[12], in[97]}), .out(out[20]));
    lut_node #(.N(4), .INIT(16'h3B2B)) lut21 (.addr({in[35], in[78], in[99], in[51]}), .out(out[21]));
    lut_node #(.N(4), .INIT(16'hA0B2)) lut22 (.addr({in[90], in[18], in[6], in[91]}), .out(out[22]));
    lut_node #(.N(4), .INIT(16'h30A3)) lut23 (.addr({in[94], in[73], in[19], in[82]}), .out(out[23]));
    lut_node #(.N(4), .INIT(16'hDCDD)) lut24 (.addr({in[15], in[22], in[61], in[17]}), .out(out[24]));
    lut_node #(.N(4), .INIT(16'h5F22)) lut25 (.addr({in[13], in[90], in[42], in[38]}), .out(out[25]));
    lut_node #(.N(4), .INIT(16'hF031)) lut26 (.addr({in[30], in[50], in[6], in[79]}), .out(out[26]));
    lut_node #(.N(4), .INIT(16'hA898)) lut27 (.addr({in[27], in[36], in[91], in[97]}), .out(out[27]));
    lut_node #(.N(4), .INIT(16'hE650)) lut28 (.addr({in[37], in[74], in[40], in[99]}), .out(out[28]));
    lut_node #(.N(4), .INIT(16'hD4E5)) lut29 (.addr({in[71], in[53], in[18], in[15]}), .out(out[29]));
    lut_node #(.N(4), .INIT(16'hFE10)) lut30 (.addr({in[44], in[59], in[78], in[5]}), .out(out[30]));
    lut_node #(.N(4), .INIT(16'hF990)) lut31 (.addr({in[68], in[45], in[10], in[1]}), .out(out[31]));
    lut_node #(.N(4), .INIT(16'hAF17)) lut32 (.addr({in[31], in[72], in[47], in[28]}), .out(out[32]));
    lut_node #(.N(4), .INIT(16'h045C)) lut33 (.addr({in[94], in[39], in[11], in[3]}), .out(out[33]));
    lut_node #(.N(4), .INIT(16'h5109)) lut34 (.addr({in[49], in[62], in[67], in[46]}), .out(out[34]));
    lut_node #(.N(4), .INIT(16'h0373)) lut35 (.addr({in[52], in[86], in[12], in[35]}), .out(out[35]));
    lut_node #(.N(4), .INIT(16'h282B)) lut36 (.addr({in[70], in[51], in[48], in[66]}), .out(out[36]));
    lut_node #(.N(4), .INIT(16'h9710)) lut37 (.addr({in[32], in[7], in[9], in[14]}), .out(out[37]));
    lut_node #(.N(4), .INIT(16'hD501)) lut38 (.addr({in[41], in[17], in[4], in[58]}), .out(out[38]));
    lut_node #(.N(4), .INIT(16'hF210)) lut39 (.addr({in[63], in[8], in[96], in[26]}), .out(out[39]));
    lut_node #(.N(4), .INIT(16'hE1A8)) lut40 (.addr({in[64], in[25], in[83], in[57]}), .out(out[40]));
    lut_node #(.N(4), .INIT(16'h10BD)) lut41 (.addr({in[55], in[33], in[88], in[65]}), .out(out[41]));
    lut_node #(.N(4), .INIT(16'h8321)) lut42 (.addr({in[82], in[21], in[56], in[81]}), .out(out[42]));
    lut_node #(.N(4), .INIT(16'h48CF)) lut43 (.addr({in[0], in[23], in[29], in[24]}), .out(out[43]));
    lut_node #(.N(4), .INIT(16'hAA19)) lut44 (.addr({in[80], in[20], in[73], in[76]}), .out(out[44]));
    lut_node #(.N(4), .INIT(16'h0111)) lut45 (.addr({in[87], in[43], in[98], in[95]}), .out(out[45]));
    lut_node #(.N(4), .INIT(16'hE0E2)) lut46 (.addr({in[22], in[34], in[16], in[85]}), .out(out[46]));
    lut_node #(.N(4), .INIT(16'h03D0)) lut47 (.addr({in[61], in[19], in[77], in[69]}), .out(out[47]));
    lut_node #(.N(4), .INIT(16'h0745)) lut48 (.addr({in[2], in[93], in[89], in[92]}), .out(out[48]));
    lut_node #(.N(4), .INIT(16'hCC8B)) lut49 (.addr({in[60], in[75], in[54], in[84]}), .out(out[49]));
    lut_node #(.N(4), .INIT(16'h0D5F)) lut50 (.addr({in[12], in[35], in[58], in[69]}), .out(out[50]));
endmodule
