// Auto-generated by rtl/generate_rtl.py from dwn_wesad_hw115_100_51_tau3.5.json.
// Do not edit by hand -- regenerate instead.

module dwn_core (
    input  wire clk,
    input  wire [459:0] in,
    output wire [50:0] out
);
    wire [99:0] layer1_comb;
    reg  [99:0] layer1_bits = 100'b0;
    dwn_layer1 u_layer1 (.in(in), .out(layer1_comb));

    wire [50:0] layer2_comb;
    reg  [50:0] layer2_bits = 51'b0;
    dwn_layer2 u_layer2 (.in(layer1_bits), .out(layer2_comb));

    always @(posedge clk) begin
        layer1_bits <= layer1_comb;
        layer2_bits <= layer2_comb;
    end

    assign out = layer2_bits;
endmodule
