// Auto-generated by rtl/generate_rtl.py from dwn_wesad_hw115_100_51_tau3.5.json.
// Do not edit by hand -- regenerate instead.

`ifndef DWN_PARAMS_VH
`define DWN_PARAMS_VH
`define DWN_IN_BITS     460
`define DWN_NUM_CLASSES 3
`define DWN_SCORE_W     5
`define DWN_NUM_LAYERS  2
`define DWN_OUT_BITS    51
`endif
