"""Fit the HRV shift/offset narrowing from a built cache and emit it as a Verilog include."""

import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "wesad" / "scripts" / "golden_models"))

from fixed_frontend import HRV_KEYS  # noqa: E402
from time_stats_golden_model import _fit_one, wrap  # noqa: E402

JSON_OUT = REPO / "wesad" / "scripts" / "golden_models" / "hrv_narrowing.json"
VH_OUT = REPO / "wesad" / "rtl" / "hrv_narrowing.vh"


def main():
    cache = Path(sys.argv[1])
    d = dict(np.load(cache, allow_pickle=True))
    X = d["X"]
    base = 115
    shift, offset = [], []
    for j, k in enumerate(HRV_KEYS):
        col = [int(v) for v in X[:, base + j]]
        sh, off = _fit_one(col, "shift")
        shift.append(sh)
        offset.append(off)
        X[:, base + j] = [wrap((v >> sh) - off, 8) for v in col]
        print(f"  {k:10s} shift {sh:2d} offset {off}")

    JSON_OUT.write_text(json.dumps({"shift": shift, "offset": offset}, indent=2) + "\n")
    lines = ["// Generated by wesad/scripts/rtl_fixtures/make_hrv_narrowing.py -- do not edit.",
             "case (write_index)"]
    for j in range(len(HRV_KEYS)):
        sign = "-" if offset[j] < 0 else ""
        lines.append(f"    3'd{j} : begin hrv_shift = 5'd{shift[j]}; "
                     f"hrv_offset = {sign}20'sd{abs(offset[j])}; end")
    lines.append("    default : begin hrv_shift = 5'd0; hrv_offset = 20'sd0; end")
    lines.append("endcase")
    VH_OUT.write_text("\n".join(lines) + "\n")

    d["X"] = X
    np.savez_compressed(cache, **d)
    print(f"narrowed HRV columns in {cache.name}; wrote {VH_OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
