"""Emit the time-path narrowing table from narrowing.json as a Verilog include."""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "wesad" / "scripts" / "golden_models" / "narrowing.json"
OUT = REPO / "wesad" / "rtl" / "narrowing.vh"

# write_index order in time_stats.sv; min and max reach the word unnarrowed
ORDER = ["mean", "std", "rms", None, None, "range", "median", "iqr", "mad", "slope"]


def main():
    d = json.loads(SRC.read_text())
    shift, offset = d["shift"], d["offset"]
    lines = ["// Generated by wesad/scripts/rtl_fixtures/make_narrowing_vh.py -- do not edit.",
             "case ({sensor_select_ff, table_index})"]
    for s in range(5):
        for i, key in enumerate(ORDER):
            sh = 0 if key is None else shift[key][s]
            off = 0 if key is None else offset[key][s]
            lines.append(f"    7'd{s * 16 + i} : begin narrow_shift = 6'd{sh}; "
                         f"narrow_offset = -13'sd{-off}; end" if off < 0 else
                         f"    7'd{s * 16 + i} : begin narrow_shift = 6'd{sh}; "
                         f"narrow_offset = 13'sd{off}; end")
    lines.append("    default : begin narrow_shift = 6'd0; narrow_offset = 13'sd0; end")
    lines.append("endcase")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
