"""Fit the PSD shift/offset narrowing over all windows and emit it as a Verilog include."""

import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "wesad" / "scripts" / "golden_models"))
sys.path.insert(0, str(REPO / "wesad" / "scripts" / "cache_builders"))

from extract_features import MODALITY_FS, PSD_BANDS  # noqa: E402
from fft_fixed_bfp import psd_power_bfp  # noqa: E402
from fixed_frontend import ADC_PROFILES, acc_magnitude_fixed, adc_quantize  # noqa: E402
from psd_features_golden_model import PSD_KEYS, band_edges, psd_features_fixed  # noqa: E402
from time_stats_golden_model import _fit_one  # noqa: E402

SENSORS = ["ECG", "ACC", "Resp", "EDA", "EMG"]
SEG_LEN = {"ECG": 2048, "EMG": 2048}
WINDOWS = REPO / "data" / "wesad_cache" / "wesad_windows_resampled6.npz"
JSON_OUT = REPO / "wesad" / "scripts" / "golden_models" / "psd_narrowing.json"
VH_OUT = REPO / "wesad" / "rtl" / "psd_narrowing.vh"
CHUNK = 256


def main():
    win = np.load(WINDOWS)
    spans, bits = ADC_PROFILES["respiban"]
    codes = {m: adc_quantize(win[m], m, spans, bits) for m in SENSORS}
    qx, qy, qz = (adc_quantize(win[f"ACC_{a}"], "ACC_axis", spans, bits) for a in "xyz")
    codes["ACC"] = np.vstack([acc_magnitude_fixed(qx[i], qy[i], qz[i])
                              for i in range(qx.shape[0])])

    shift = [[0] * len(PSD_KEYS) for _ in SENSORS]
    offset = [[0] * len(PSD_KEYS) for _ in SENSORS]
    for s, mod in enumerate(SENSORS):
        edges = band_edges(MODALITY_FS[mod], 2048, PSD_BANDS)
        raw = [[] for _ in PSD_KEYS]
        n = codes[mod].shape[0]
        for lo in range(0, n, CHUNK):
            acc, pe, _ = psd_power_bfp(codes[mod][lo:lo + CHUNK], SEG_LEN.get(mod),
                                       2048, 8, detrend=True)
            for r in range(acc.shape[0]):
                f = psd_features_fixed(acc[r], pe[r], edges)
                for j, k in enumerate(PSD_KEYS):
                    raw[j].append(int(f[k]))
        for j, k in enumerate(PSD_KEYS):
            shift[s][j], offset[s][j] = _fit_one(raw[j], "shift")
        print(f"{mod:5} " + " ".join(f"{PSD_KEYS[j]}:{shift[s][j]}/{offset[s][j]}"
                                     for j in range(len(PSD_KEYS))))

    JSON_OUT.write_text(json.dumps({"shift": shift, "offset": offset}, indent=2) + "\n")
    lines = ["// Generated by wesad/scripts/rtl_fixtures/make_psd_narrowing.py -- do not edit.",
             "case ({modality, write_index})"]
    for s in range(len(SENSORS)):
        for j in range(len(PSD_KEYS)):
            sh, off = shift[s][j], offset[s][j]
            sign = "-" if off < 0 else ""
            lines.append(f"    7'd{s * 16 + j} : begin psd_shift = 5'd{sh}; "
                         f"psd_offset = {sign}21'sd{abs(off)}; end")
    lines.append("    default : begin psd_shift = 5'd0; psd_offset = 21'sd0; end")
    lines.append("endcase")
    VH_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {JSON_OUT} and {VH_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
