// Generated by wesad/scripts/rtl_fixtures/make_hrv_narrowing.py -- do not edit.
case (write_index)
    3'd0 : begin hrv_shift = 5'd7; hrv_offset = 20'sd184; end
    3'd1 : begin hrv_shift = 5'd8; hrv_offset = 20'sd198; end
    3'd2 : begin hrv_shift = 5'd8; hrv_offset = 20'sd119; end
    3'd3 : begin hrv_shift = 5'd9; hrv_offset = 20'sd90; end
    3'd4 : begin hrv_shift = 5'd0; hrv_offset = 20'sd117; end
    3'd5 : begin hrv_shift = 5'd0; hrv_offset = 20'sd150; end
    3'd6 : begin hrv_shift = 5'd2; hrv_offset = 20'sd150; end
    3'd7 : begin hrv_shift = 5'd0; hrv_offset = 20'sd185; end
    default : begin hrv_shift = 5'd0; hrv_offset = 20'sd0; end
endcase
